name: investment_insights
description: FinView Lite - Investment Dashboard
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/portfolio.json
